# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunPipeline = channel.unary_unary(
                '/agent.AgentService/RunPipeline',
                request_serializer=agent__pb2.PipelineRequest.SerializeToString,
                response_deserializer=agent__pb2.PipelineResponse.FromString,
                _registered_method=True)
        self.StartWatcher = channel.unary_unary(
                '/agent.AgentService/StartWatcher',
                request_serializer=agent__pb2.WatcherConfig.SerializeToString,
                response_deserializer=agent__pb2.WatcherResponse.FromString,
                _registered_method=True)
        self.StopWatcher = channel.unary_unary(
                '/agent.AgentService/StopWatcher',
                request_serializer=agent__pb2.Empty.SerializeToString,
                response_deserializer=agent__pb2.WatcherResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/agent.AgentService/GetStatus',
                request_serializer=agent__pb2.Empty.SerializeToString,
                response_deserializer=agent__pb2.AgentStatus.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/agent.AgentService/HealthCheck',
                request_serializer=agent__pb2.Empty.SerializeToString,
                response_deserializer=agent__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.TriggerDiscovery = channel.unary_unary(
                '/agent.AgentService/TriggerDiscovery',
                request_serializer=agent__pb2.DiscoveryRequest.SerializeToString,
                response_deserializer=agent__pb2.DiscoveryResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/agent.AgentService/StreamEvents',
                request_serializer=agent__pb2.EventSubscription.SerializeToString,
                response_deserializer=agent__pb2.PipelineEvent.FromString,
                _registered_method=True)


class AgentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RunPipeline(self, request, context):
        """Start a pipeline run for specific posts with optional step filtering
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartWatcher(self, request, context):
        """Start the autonomous content watcher loop
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopWatcher(self, request, context):
        """Gracefully stop the watcher (finishes current video, then stops)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get combined status: pipeline state, watcher state, disk usage, OBS/Chrome health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check: is the machine up, OBS running, Chrome available, disk OK
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerDiscovery(self, request, context):
        """Run Patreon content discovery (fetch new posts)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Server-streaming: real-time pipeline events pushed to client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.RunPipeline,
                    request_deserializer=agent__pb2.PipelineRequest.FromString,
                    response_serializer=agent__pb2.PipelineResponse.SerializeToString,
            ),
            'StartWatcher': grpc.unary_unary_rpc_method_handler(
                    servicer.StartWatcher,
                    request_deserializer=agent__pb2.WatcherConfig.FromString,
                    response_serializer=agent__pb2.WatcherResponse.SerializeToString,
            ),
            'StopWatcher': grpc.unary_unary_rpc_method_handler(
                    servicer.StopWatcher,
                    request_deserializer=agent__pb2.Empty.FromString,
                    response_serializer=agent__pb2.WatcherResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=agent__pb2.Empty.FromString,
                    response_serializer=agent__pb2.AgentStatus.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=agent__pb2.Empty.FromString,
                    response_serializer=agent__pb2.HealthResponse.SerializeToString,
            ),
            'TriggerDiscovery': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerDiscovery,
                    request_deserializer=agent__pb2.DiscoveryRequest.FromString,
                    response_serializer=agent__pb2.DiscoveryResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=agent__pb2.EventSubscription.FromString,
                    response_serializer=agent__pb2.PipelineEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/RunPipeline',
            agent__pb2.PipelineRequest.SerializeToString,
            agent__pb2.PipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartWatcher(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/StartWatcher',
            agent__pb2.WatcherConfig.SerializeToString,
            agent__pb2.WatcherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopWatcher(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/StopWatcher',
            agent__pb2.Empty.SerializeToString,
            agent__pb2.WatcherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/GetStatus',
            agent__pb2.Empty.SerializeToString,
            agent__pb2.AgentStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/HealthCheck',
            agent__pb2.Empty.SerializeToString,
            agent__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerDiscovery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/TriggerDiscovery',
            agent__pb2.DiscoveryRequest.SerializeToString,
            agent__pb2.DiscoveryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent.AgentService/StreamEvents',
            agent__pb2.EventSubscription.SerializeToString,
            agent__pb2.PipelineEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
